---
dist: xenial
language: ruby
python:
  - 3.7
jdk:
  - openjdk11
cache: bundler
rvm:
  - jruby-9.2.11.0
  - 2.7.0
before_install:
  - wget https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py --user
  - python3 -m pip install --user git+https://github.com/klobuczek/boltkit@1.3#egg=boltkit
  - neoctrl-install $NEO4J_EDITION_FLAG $NEO4J_VERSION servers
  - if [ -n "$NEO4J_EDITION_FLAG" ]; then NEO4J_EDITION=enterprise; else NEO4J_EDITION=community; fi
  - NEO4J_DIR=servers/neo4j-$NEO4J_EDITION-$NEO4J_VERSION
  - neoctrl-configure $NEO4J_DIR dbms.memory.pagecache.size=600m dbms.memory.heap.max_size=600m dbms.memory.heap.initial_size=600m dbms.directories.import=
  #dbms.connectors.default_listen_address=::
install:
  - neoctrl-set-initial-password password $NEO4J_DIR
  - neoctrl-start $NEO4J_DIR
  - wget https://github.com/neo4j-drivers/seabolt/releases/download/v1.7.4/seabolt-1.7.4-Linux-ubuntu-16.04.deb
  - sudo dpkg -i seabolt-1.7.4-Linux-ubuntu-16.04.deb
before_script: bin/setup
env:
  global:
    - JRUBY_OPTS="-J-Xmx1024m -Xcompile.invokedynamic=false -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-noverify -Xcompile.mode=OFF"
    - NEO4J_EDITION_FLAG=-e
    - NEO4J_BOLT_URL="bolt://127.0.0.1:7687"
    - PATH=$PATH:~/.local/bin
  matrix:
    - NEO4J_VERSION=4.0.2
    - NEO4J_VERSION=3.5.16
matrix:
  include:
    - env: NEO4J_VERSION=4.0.2 driver=java
    - env: NEO4J_VERSION=3.5.16 driver=java
    - jdk: openjdk8
      env: NEO4J_VERSION=3.4.17
    - jdk: openjdk8
      env: NEO4J_VERSION=3.4.17 driver=java
    - rvm: 2.5.7
      env: NEO4J_VERSION=4.0.2 NEO4J_EDITION_FLAG=
    - rvm: 2.6.5
      env: NEO4J_VERSION=4.0.2 NEO4J_EDITION_FLAG=
    - jdk: openjdk8
      rvm: 2.7.0
      env: NEO4J_VERSION=3.4.17
after_failure:
  - cat $NEO4J_DIR/logs/neo4j.log
  - cat $NEO4J_DIR/logs/debug.log
  - cat $NEO4J_DIR/conf/neo4j.conf