---
#os: linux
#arch: arm64
dist: xenial
sudo: false
language: ruby
python:
  - 3.7
jdk:
  - openjdk8
  - openjdk11
cache: bundler
rvm:
  - jruby-9.2.9.0
  - 2.6.5
before_install:
  - wget https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py --user
  - python3 -m pip install --user git+https://github.com/klobuczek/boltkit@1.3#egg=boltkit
  - neoctrl-install $NEO4J_EDITION_FLAG $NEO4J_VERSION servers
  - if [ -n "$NEO4J_EDITION_FLAG" ]; then NEO4J_EDITION=enterprise; else NEO4J_EDITION=community; fi
  - NEO4J_DIR=servers/neo4j-$NEO4J_EDITION-$NEO4J_VERSION
  - neoctrl-configure $NEO4J_DIR dbms.memory.pagecache.size=600m dbms.memory.heap.max_size=600m dbms.memory.heap.initial_size=600m
#    dbms.connectors.default_listen_address='::'
install:
  - neoctrl-set-initial-password password $NEO4J_DIR
  - neoctrl-start $NEO4J_DIR
  - "curl -L https://github.com/neo4j-drivers/seabolt/releases/download/v1.7.4/seabolt-1.7.4-Linux-ubuntu-16.04.tar.gz | tar -xz"
before_script: bin/setup
env:
  global:
    - JRUBY_OPTS="-J-Xmx1024m -Xcompile.invokedynamic=false -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-noverify -Xcompile.mode=OFF"
    - NEO4J_EDITION_FLAG=-e
    - NEO4J_BOLT_URL="bolt://127.0.0.1:7687"
    - SEABOLT_LIB=./seabolt-1.7.4-Linux-ubuntu-16.04/usr/local/lib/libseabolt17.so
    - PATH=$PATH:~/.local/bin
  matrix:
    - NEO4J_VERSION=3.5.12
    - NEO4J_VERSION=3.4.16
    - NEO4J_VERSION=3.5.12 SEABOLT_LIB=
    - NEO4J_VERSION=3.4.16 SEABOLT_LIB=
matrix:
  include:
    - rvm: 2.5.7
      env: NEO4J_VERSION=3.5.12 NEO4J_EDITION_FLAG=
    - jdk: openjdk11
      rvm: jruby-9.2.8.0
      env: NEO4J_VERSION=3.5.12 SEABOLT_LIB=
  exclude:
    - rvm: 2.6.5
      env: NEO4J_VERSION=3.5.12 SEABOLT_LIB=
    - rvm: 2.6.5
      env: NEO4J_VERSION=3.4.16 SEABOLT_LIB=
    - jdk: openjdk11
      env: NEO4J_VERSION=3.4.16
    - jdk: openjdk11
      env: NEO4J_VERSION=-3.4.16 SEABOLT_LIB=
  allow_failures:
    - jdk: openjdk11
      rvm: jruby-9.2.9.0
      env: NEO4J_VERSION=3.5.12 SEABOLT_LIB=
after_failure:
  - cat $NEO4J_DIR/logs/neo4j.log
  - cat $NEO4J_DIR/logs/debug.log
  - cat $NEO4J_DIR/conf/neo4j.conf